
export const initialRoutes = {
  informes: "/dashboard/informes/generar-credenciales",
  unidadAcademica: "/dashboard/unidad-academica/gestionar-cursos",
  alumno: "/alumno/matricula",
  docente: "/dashboard/docente/gestionar-actas",
  supervisor: "/dashboard/supervisor/gestionar-inscripciones?page=1",
  admin: "/dashboard",
}

export const rolesDictionary = {
  informes: "Informes",
  unidadAcademica: "Unidad Académica",
  alumno: "Alumno",
  docente: "Docente",
  supervisor: "Supervisor",
  admin: "Administrador",
}

export const courseHeaders = [
  {
    id: 1,
    name: "Curso",
  },
  {
    id: 2,
    name: "Código",
  },
  {
    id: 3,
    name: "No de módulos",
  },
  {
    id: 4,
    name: "Horas (CERT-DICT)",
  },
  {
    id: 5,
    name: "Costo por hora (S/.)",
  },
  {
    id: 6,
    name: "Pago docente (S/.)",
  },
  {
    id: 7,
    name: "Acciones",
  },
]

export const studentHeaders = [
  {
    id: 1,
    name: "Apellidos",
  },
  {
    id: 2,
    name: "Nombres",
  },
  {
    id: 3,
    name: "Banco Alumno",
  },
  {
    id: 4,
    name: "No. de operación",
  },
  {
    id: 5,
    name: "Monto (S/.)",
  },
  {
    id: 6,
    name: "Fecha de pago",
  },
  {
    id: 7,
    name: "Telefono",
  },
  {
    id: 8,
    name: "Acciones",
  },
]

export const studentHeadersReadOnly = [
  {
    id: 1,
    name: "Apellidos",
  },
  {
    id: 2,
    name: "Nombres",
  },
  {
    id: 3,
    name: "Tipo de doc.",
  },
  {
    id: 4,
    name: "No. de doc.",
  },
  {
    id: 5,
    name: "Teléfono",
  },
  {
    id: 6,
    name: "Correo",
  },
]

export const teacherHeaders = [
  {
    id: 1,
    name: "Apellidos",
  },
  {
    id: 2,
    name: "Nombres",
  },
  {
    id: 3,
    name: "Tipo de doc.",
  },
  {
    id: 4,
    name: "No. de doc.",
  },
  {
    id: 5,
    name: "Teléfono",
  },
  {
    id: 6,
    name: "Correo",
  },
  {
    id: 7,
    name: "Acciones",
  },
]

export const gradesHeaders = [
  {
    id: 1,
    name: "Apellidos",
  },
  {
    id: 2,
    name: "Nombres",
  },
  {
    id: 3,
    name: "Tipo de doc.",
  },
  {
    id: 4,
    name: "No. de doc.",
  },
  {
    id: 5,
    name: "Teléfono",
  },
  {
    id: 6,
    name: "Notas",
  },
  {
    id: 7,
    name: "Promedio",
  },
]

export const reportGroupsHeaders = [
  {
    id: 1,
    name: "Curso",
  },
  {
    id: 2,
    name: "Código",
  },
  {
    id: 3,
    name: "Fecha de inicio",
  },
  {
    id: 4,
    name: "Nota final",
  },
]

export const groupHeaders = [
  {
    id: 1,
    name: "Curso",
  },
  {
    id: 2,
    name: "Módulo",
  },
  {
    id: 3,
    name: "No. de Grupo",
  },
  {
    id: 4,
    name: "Código",
  },
  {
    id: 5,
    name: "Horario",
  },
  {
    id: 6,
    name: "Matriculados",
  },
  {
    id: 7,
    name: "Acciones",
  },
]

export const certificateHeaders = [
  {
    id: 1,
    name: "Curso",
  },
  {
    id: 2,
    name: "Código",
  },
  {
    id: 3,
    name: "Acciones",
  },
]

export const payDetailsHeaders = [
  {
    id: 1,
    name: "Nro. de operación",
  },
  {
    id: 2,
    name: "Monto (S/.)",
  },
  {
    id: 3,
    name: "Banco alumno",
  },
  {
    id: 4,
    name: "Banco UNMSM",
  },
  {
    id: 5,
    name: "Fecha de pago",
  },
  {
    id: 6,
    name: "Estado",
  },
  {
    id: 7,
    name: "Creado",
  },
]

export const documentsHeaders = [
  {
    id: 1,
    name: "Fecha de generación",
  },
  {
    id: 2,
    name: "Reporte en Excel",
  },
  {
    id: 3,
    name: "Reporte en PDF",
  },
]

export const coursesData = [
  {
    id: 1,
    name: "Experto en Microsoft Excel",
    codigo: "CV-EMEX2021",
    numeroDeModulos: 3,
    horasCertificadas: 21,
    horasDictadas: 18,
    costoPorHora: 110,
  },
  {
    id: 2,
    name: "Regulacion de las Telecomunicaciones",
    codigo: "CV-RETE2021",
    numeroDeModulos: 3,
    horasCertificadas: 21,
    horasDictadas: 18,
    costoPorHora: 100,
  },
  {
    id: 3,
    name: "Formacion de Formadores",
    codigo: "CV-FF2021",
    numeroDeModulos: 3,
    horasCertificadas: 21,
    horasDictadas: 18,
    costoPorHora: 100,
  },
  {
    id: 4,
    name: "Especialista en Ofimatica Acelerado",
    codigo: "CV-ESOA2021",
    numeroDeModulos: 3,
    horasCertificadas: 21,
    horasDictadas: 18,
    costoPorHora: 160,
  },
  {
    id: 5,
    name: "Especialista en Marketing Digital",
    codigo: "CV-MD2021",
    numeroDeModulos: 3,
    horasCertificadas: 21,
    horasDictadas: 18,
    costoPorHora: 130,
  },
  {
    id: 6,
    name: "Analisis Estadistico con SPSS",
    codigo: "CV-AESPS2021",
    numeroDeModulos: 3,
    horasCertificadas: 21,
    horasDictadas: 18,
    costoPorHora: 100,
  },
  {
    id: 7,
    name: "Tablas dinamicas con Microsoft Excel 2019",
    codigo: "CV-TDE2021",
    numeroDeModulos: 3,
    horasCertificadas: 21,
    horasDictadas: 18,
    costoPorHora: 80,
  },
  {
    id: 8,
    name: "Formacion de Formadores",
    codigo: "CV-FF2021",
    numeroDeModulos: 3,
    horasCertificadas: 21,
    horasDictadas: 18,
    costoPorHora: 100,
  },
  {
    id: 9,
    name: "Especialista en Marketing Digital",
    codigo: "CV-MD2021",
    numeroDeModulos: 3,
    horasCertificadas: 21,
    horasDictadas: 18,
    costoPorHora: 130,
  },
  {
    id: 10,
    name: "Analisis Estadistico con SPSS",
    codigo: "CV-AESPS2021",
    numeroDeModulos: 3,
    horasCertificadas: 21,
    horasDictadas: 18,
    costoPorHora: 100,
  },
  {
    id: 11,
    name: "Tablas dinamicas con Microsoft Excel 2019",
    codigo: "CV-TDE2021",
    numeroDeModulos: 3,
    horasCertificadas: 21,
    horasDictadas: 18,
    costoPorHora: 80,
  },
  {
    id: 12,
    name: "Formacion de Formadores",
    codigo: "CV-FF2021",
    numeroDeModulos: 3,
    horasCertificadas: 21,
    horasDictadas: 18,
    costoPorHora: 100,
  },
  {
    id: 13,
    name: "Especialista en Marketing Digital",
    codigo: "CV-MD2021",
    numeroDeModulos: 3,
    horasCertificadas: 21,
    horasDictadas: 18,
    costoPorHora: 130,
  },
  {
    id: 14,
    name: "Analisis Estadistico con SPSS",
    codigo: "CV-AESPS2021",
    numeroDeModulos: 3,
    horasCertificadas: 21,
    horasDictadas: 18,
    costoPorHora: 100,
  },
  {
    id: 15,
    name: "Tablas dinamicas con Microsoft Excel 2019",
    codigo: "CV-TDE2021",
    numeroDeModulos: 3,
    horasCertificadas: 21,
    horasDictadas: 18,
    costoPorHora: 80,
  },
  {
    id: 16,
    name: "Formacion de Formadores",
    codigo: "CV-FF2021",
    numeroDeModulos: 3,
    horasCertificadas: 21,
    horasDictadas: 18,
    costoPorHora: 100,
  },
  {
    id: 17,
    name: "Especialista en Marketing Digital",
    codigo: "CV-MD2021",
    numeroDeModulos: 3,
    horasCertificadas: 21,
    horasDictadas: 18,
    costoPorHora: 130,
  },
  {
    id: 18,
    name: "Analisis Estadistico con SPSS",
    codigo: "CV-AESPS2021",
    numeroDeModulos: 3,
    horasCertificadas: 21,
    horasDictadas: 18,
    costoPorHora: 100,
  },
  {
    id: 19,
    name: "Tablas dinamicas con Microsoft Excel 2019",
    codigo: "CV-TDE2021",
    numeroDeModulos: 3,
    horasCertificadas: 21,
    horasDictadas: 18,
    costoPorHora: 80,
  },
  {
    id: 20,
    name: "Formacion de Formadores",
    codigo: "CV-FF2021",
    numeroDeModulos: 3,
    horasCertificadas: 21,
    horasDictadas: 18,
    costoPorHora: 100,
  },
  {
    id: 21,
    name: "Especialista en Marketing Digital",
    codigo: "CV-MD2021",
    numeroDeModulos: 3,
    horasCertificadas: 21,
    horasDictadas: 18,
    costoPorHora: 130,
  },
  {
    id: 22,
    name: "Analisis Estadistico con SPSS",
    codigo: "CV-AESPS2021",
    numeroDeModulos: 3,
    horasCertificadas: 21,
    horasDictadas: 18,
    costoPorHora: 100,
  },
  {
    id: 23,
    name: "Tablas dinamicas con Microsoft Excel 2019",
    codigo: "CV-TDE2021",
    numeroDeModulos: 3,
    horasCertificadas: 21,
    horasDictadas: 18,
    costoPorHora: 80,
  },
  {
    id: 24,
    name: "Formacion de Formadores",
    codigo: "CV-FF2021",
    numeroDeModulos: 3,
    horasCertificadas: 21,
    horasDictadas: 18,
    costoPorHora: 100,
  },
  {
    id: 25,
    name: "Especialista en Marketing Digital",
    codigo: "CV-MD2021",
    numeroDeModulos: 3,
    horasCertificadas: 21,
    horasDictadas: 18,
    costoPorHora: 130,
  },
  {
    id: 26,
    name: "Analisis Estadistico con SPSS",
    codigo: "CV-AESPS2021",
    numeroDeModulos: 3,
    horasCertificadas: 21,
    horasDictadas: 18,
    costoPorHora: 100,
  },
  {
    id: 27,
    name: "Tablas dinamicas con Microsoft Excel 2019",
    codigo: "CV-TDE2021",
    numeroDeModulos: 3,
    horasCertificadas: 21,
    horasDictadas: 18,
    costoPorHora: 80,
  },
  {
    id: 28,
    name: "Formacion de Formadores",
    codigo: "CV-FF2021",
    numeroDeModulos: 3,
    horasCertificadas: 21,
    horasDictadas: 18,
    costoPorHora: 100,
  },
  {
    id: 29,
    name: "Especialista en Marketing Digital",
    codigo: "CV-MD2021",
    numeroDeModulos: 3,
    horasCertificadas: 21,
    horasDictadas: 18,
    costoPorHora: 130,
  },
  {
    id: 30,
    name: "Analisis Estadistico con SPSS",
    codigo: "CV-AESPS2021",
    numeroDeModulos: 3,
    horasCertificadas: 21,
    horasDictadas: 18,
    costoPorHora: 100,
  },
  {
    id: 31,
    name: "Tablas dinamicas con Microsoft Excel 2019",
    codigo: "CV-TDE2021",
    numeroDeModulos: 3,
    horasCertificadas: 21,
    horasDictadas: 18,
    costoPorHora: 80,
  },
  {
    id: 32,
    name: "Formacion de Formadores",
    codigo: "CV-FF2021",
    numeroDeModulos: 3,
    horasCertificadas: 21,
    horasDictadas: 18,
    costoPorHora: 100,
  },
  {
    id: 33,
    name: "Especialista en Marketing Digital",
    codigo: "CV-MD2021",
    numeroDeModulos: 3,
    horasCertificadas: 21,
    horasDictadas: 18,
    costoPorHora: 130,
  },
  {
    id: 34,
    name: "Analisis Estadistico con SPSS",
    codigo: "CV-AESPS2021",
    numeroDeModulos: 3,
    horasCertificadas: 21,
    horasDictadas: 18,
    costoPorHora: 100,
  },
  {
    id: 35,
    name: "Tablas dinamicas con Microsoft Excel 2019",
    codigo: "CV-TDE2021",
    numeroDeModulos: 3,
    horasCertificadas: 21,
    horasDictadas: 18,
    costoPorHora: 80,
  },
  {
    id: 36,
    name: "Formacion de Formadores",
    codigo: "CV-FF2021",
    numeroDeModulos: 3,
    horasCertificadas: 21,
    horasDictadas: 18,
    costoPorHora: 100,
  },
  {
    id: 37,
    name: "Especialista en Marketing Digital",
    codigo: "CV-MD2021",
    numeroDeModulos: 3,
    horasCertificadas: 21,
    horasDictadas: 18,
    costoPorHora: 130,
  },
  {
    id: 38,
    name: "Analisis Estadistico con SPSS",
    codigo: "CV-AESPS2021",
    numeroDeModulos: 3,
    horasCertificadas: 21,
    horasDictadas: 18,
    costoPorHora: 100,
  },
  {
    id: 39,
    name: "Tablas dinamicas con Microsoft Excel 2019",
    codigo: "CV-TDE2021",
    numeroDeModulos: 3,
    horasCertificadas: 21,
    horasDictadas: 18,
    costoPorHora: 80,
  },
  {
    id: 40,
    name: "Formacion de Formadores",
    codigo: "CV-FF2021",
    numeroDeModulos: 3,
    horasCertificadas: 21,
    horasDictadas: 18,
    costoPorHora: 100,
  },
  {
    id: 41,
    name: "Especialista en Marketing Digital",
    codigo: "CV-MD2021",
    numeroDeModulos: 3,
    horasCertificadas: 21,
    horasDictadas: 18,
    costoPorHora: 130,
  },
  {
    id: 42,
    name: "Analisis Estadistico con SPSS",
    codigo: "CV-AESPS2021",
    numeroDeModulos: 3,
    horasCertificadas: 21,
    horasDictadas: 18,
    costoPorHora: 100,
  },
  {
    id: 43,
    name: "Tablas dinamicas con Microsoft Excel 2019",
    codigo: "CV-TDE2021",
    numeroDeModulos: 3,
    horasCertificadas: 21,
    horasDictadas: 18,
    costoPorHora: 80,
  },
  {
    id: 44,
    name: "Formacion de Formadores",
    codigo: "CV-FF2021",
    numeroDeModulos: 3,
    horasCertificadas: 21,
    horasDictadas: 18,
    costoPorHora: 100,
  },
  {
    id: 45,
    name: "Especialista en Marketing Digital",
    codigo: "CV-MD2021",
    numeroDeModulos: 3,
    horasCertificadas: 21,
    horasDictadas: 18,
    costoPorHora: 130,
  },
  {
    id: 46,
    name: "Analisis Estadistico con SPSS",
    codigo: "CV-AESPS2021",
    numeroDeModulos: 3,
    horasCertificadas: 21,
    horasDictadas: 18,
    costoPorHora: 100,
  },
  {
    id: 47,
    name: "Tablas dinamicas con Microsoft Excel 2019",
    codigo: "CV-TDE2021",
    numeroDeModulos: 3,
    horasCertificadas: 21,
    horasDictadas: 18,
    costoPorHora: 80,
  },
  {
    id: 48,
    name: "Formacion de Formadores",
    codigo: "CV-FF2021",
    numeroDeModulos: 3,
    horasCertificadas: 21,
    horasDictadas: 18,
    costoPorHora: 100,
  },
  {
    id: 49,
    name: "Especialista en Marketing Digital",
    codigo: "CV-MD2021",
    numeroDeModulos: 3,
    horasCertificadas: 21,
    horasDictadas: 18,
    costoPorHora: 130,
  },
  {
    id: 50,
    name: "Analisis Estadistico con SPSS",
    codigo: "CV-AESPS2021",
    numeroDeModulos: 3,
    horasCertificadas: 21,
    horasDictadas: 18,
    costoPorHora: 100,
  },
  {
    id: 51,
    name: "Tablas dinamicas con Microsoft Excel 2019",
    codigo: "CV-TDE2021",
    numeroDeModulos: 3,
    horasCertificadas: 21,
    horasDictadas: 18,
    costoPorHora: 80,
  },
  {
    id: 52,
    name: "Formacion de Formadores",
    codigo: "CV-FF2021",
    numeroDeModulos: 3,
    horasCertificadas: 21,
    horasDictadas: 18,
    costoPorHora: 100,
  },
  {
    id: 53,
    name: "Especialista en Marketing Digital",
    codigo: "CV-MD2021",
    numeroDeModulos: 3,
    horasCertificadas: 21,
    horasDictadas: 18,
    costoPorHora: 130,
  },
  {
    id: 54,
    name: "Analisis Estadistico con SPSS",
    codigo: "CV-AESPS2021",
    numeroDeModulos: 3,
    horasCertificadas: 21,
    horasDictadas: 18,
    costoPorHora: 100,
  },
  {
    id: 55,
    name: "Tablas dinamicas con Microsoft Excel 2019",
    codigo: "CV-TDE2021",
    numeroDeModulos: 3,
    horasCertificadas: 21,
    horasDictadas: 18,
    costoPorHora: 80,
  },
  {
    id: 56,
    name: "Formacion de Formadores",
    codigo: "CV-FF2021",
    numeroDeModulos: 3,
    horasCertificadas: 21,
    horasDictadas: 18,
    costoPorHora: 100,
  },
  {
    id: 57,
    name: "Especialista en Marketing Digital",
    codigo: "CV-MD2021",
    numeroDeModulos: 3,
    horasCertificadas: 21,
    horasDictadas: 18,
    costoPorHora: 130,
  },
  {
    id: 58,
    name: "Analisis Estadistico con SPSS",
    codigo: "CV-AESPS2021",
    numeroDeModulos: 3,
    horasCertificadas: 21,
    horasDictadas: 18,
    costoPorHora: 100,
  },
]

export const studentData = [
  {
    id: 1,
    apellidos: "Rodríguez Mendoza",
    nombres: "María José",
    bancoAlumno: "BBVA",
    numeroOperacion: "89-26",
    monto: "200",
    fechaPago: "01-02-2021",
    telefono: "988888888",
  },
  {
    id: 2,
    apellidos: "Espinoza Chávez",
    nombres: "Juan Carlos",
    bancoAlumno: "Interbank",
    numeroOperacion: "0519189",
    monto: "300",
    fechaPago: "02-04-2021",
    telefono: "988888888",
  },
  {
    id: 3,
    apellidos: "Vargas Gutiérrez",
    nombres: "César Augusto",
    bancoAlumno: "BBVA",
    numeroOperacion: "55-13",
    monto: "400",
    fechaPago: "03-06-2021",
    telefono: "988888888",
  },
  {
    id: 4,
    apellidos: "Romero De la Cruz",
    nombres: "Juan Manuel",
    bancoAlumno: "BBVA",
    numeroOperacion: "74-48",
    monto: "500",
    fechaPago: "04-08-2021",
    telefono: "988888888",
  },
  {
    id: 5,
    apellidos: "Martínez Reyes",
    nombres: "Pedro Daniel",
    bancoAlumno: "Scotiabank",
    numeroOperacion: "0501120010",
    monto: "600",
    fechaPago: "05-10-2021",
    telefono: "988888888",
  },
  {
    id: 6,
    apellidos: "Córdova Gómez",
    nombres: "Edwin César",
    bancoAlumno: "BCP",
    numeroOperacion: "78857966",
    monto: "700",
    fechaPago: "06-12-2021",
    telefono: "988888888",
  },
  {
    id: 7,
    apellidos: "Ramírez Salazar ",
    nombres: "Walter Fernando",
    bancoAlumno: "Interbank",
    numeroOperacion: "0519189",
    monto: "800",
    fechaPago: "07-02-2022",
    telefono: "988888888",
  },
  {
    id: 8,
    apellidos: "Rojas Pérez",
    nombres: "Jorge Luis",
    bancoAlumno: "BBVA",
    numeroOperacion: "89-26",
    monto: "900",
    fechaPago: "08-04-2022",
    telefono: "988888888",
  },
  {
    id: 9,
    apellidos: "González López",
    nombres: "Carlos Alberto",
    bancoAlumno: "Interbank",
    numeroOperacion: "55-13",
    monto: "1000",
    fechaPago: "09-06-2022",
    telefono: "988888888",
  },
  {
    id: 10,
    apellidos: "Pérez Pérez",
    nombres: "José Alberto",
    bancoAlumno: "BBVA",
    numeroOperacion: "74-48",
    monto: "1100",
    fechaPago: "10-08-2022",
    telefono: "988888888",
  },
  {
    id: 11,
    apellidos: "González López",
    nombres: "Carlos Alberto",
    bancoAlumno: "Scotiabank",
    numeroOperacion: "0501120010",
    monto: "1200",
    fechaPago: "11-10-2022",
    telefono: "988888888",
  },
  {
    id: 12,
    apellidos: "Córdova Gómez",
    nombres: "Edwin César",
    bancoAlumno: "BCP",
    numeroOperacion: "78857966",
    monto: "1300",
    fechaPago: "12-12-2022",
    telefono: "988888888",
  },
  {
    id: 13,
    apellidos: "Ramírez Salazar ",
    nombres: "Walter Fernando",
    bancoAlumno: "Interbank",
    numeroOperacion: "0519189",
    monto: "1400",
    fechaPago: "13-02-2023",
    telefono: "988888888",
  },
  {
    id: 14,
    apellidos: "Rojas Pérez",
    nombres: "Jorge Luis",
    bancoAlumno: "BBVA",
    numeroOperacion: "89-26",
    monto: "1500",
    fechaPago: "14-04-2023",
    telefono: "988888888",
  },
  {
    id: 15,
    apellidos: "González López",
    nombres: "Carlos Alberto",
    bancoAlumno: "Interbank",
    numeroOperacion: "55-13",
    monto: "1600",
    fechaPago: "15-06-2023",
    telefono: "988888888",
  },
  {
    id: 16,
    apellidos: "Pérez Pérez",
    nombres: "José Alberto",
    bancoAlumno: "BBVA",
    numeroOperacion: "74-48",
    monto: "1700",
    fechaPago: "16-08-2023",
    telefono: "988888888",
  },
  {
    id: 17,
    apellidos: "González López",
    nombres: "Carlos Alberto",
    bancoAlumno: "Scotiabank",
    numeroOperacion: "0501120010",
    monto: "1800",
    fechaPago: "17-10-2023",
    telefono: "988888888",
  },
  {
    id: 18,
    apellidos: "Córdova Gómez",
    nombres: "Edwin César",
    bancoAlumno: "BCP",
    numeroOperacion: "78857966",
    monto: "1900",
    fechaPago: "18-12-2023",
    telefono: "988888888",
  },
  {
    id: 19,
    apellidos: "Ramírez Salazar ",
    nombres: "Walter Fernando",
    bancoAlumno: "Interbank",
    numeroOperacion: "0519189",
    monto: "2000",
    fechaPago: "19-02-2024",
    telefono: "988888888",
  },
  {
    id: 20,
    apellidos: "Rojas Pérez",
    nombres: "Jorge Luis",
    bancoAlumno: "BBVA",
    numeroOperacion: "89-26",
    monto: "2100",
    fechaPago: "20-04-2024",
    telefono: "988888888",
  },
  {
    id: 21,
    apellidos: "González López",
    nombres: "Carlos Alberto",
    bancoAlumno: "Interbank",
    numeroOperacion: "55-13",
    monto: "200",
    fechaPago: "21-06-2024",
    telefono: "988888888",
  },
  {
    id: 22,
    apellidos: "Pérez Pérez",
    nombres: "José Alberto",
    bancoAlumno: "BBVA",
    numeroOperacion: "74-48",
    monto: "2300",
    fechaPago: "22-08-2024",
    telefono: "9888888",
  },
  {
    id: 23,
    apellidos: "González López",
    nombres: "Carlos Alberto",
    bancoAlumno: "Scotiabank",
    numeroOperacion: "0501120010",
    monto: "400",
    fechaPago: "23-10-2024",
    telefono: "988888888",
  },
  {
    id: 24,
    apellidos: "Córdova Gómez",
    nombres: "Edwin César",
    bancoAlumno: "BCP",
    numeroOperacion: "78857966",
    monto: "2500",
    fechaPago: "24-12-2024",
    telefono: "988888888",
  },
  {
    id: 25,
    apellidos: "Ramírez Salazar ",
    nombres: "Walter Fernando",
    bancoAlumno: "Interbank",
    numeroOperacion: "0519189",
    monto: "600",
    fechaPago: "25-02-2025",
    telefono: "988888888",
  },
  {
    id: 26,
    apellidos: "Rojas Pérez",
    nombres: "Jorge Luis",
    bancoAlumno: "BBVA",
    numeroOperacion: "89-26",
    monto: "700",
    fechaPago: "26-04-2025",
    telefono: "988888888",
  },
  {
    id: 27,
    apellidos: "González López",
    nombres: "Carlos Alberto",
    bancoAlumno: "Interbank",
    numeroOperacion: "55-13",
    monto: "800",
    fechaPago: "27-06-2025",
    telefono: "988888888",
  },
]

export const teacherData = [
  {
    id: 1,
    apellidos: "Rodríguez Mendoza",
    nombres: "María José",
    tipo_documento: "DNI",
    nro_documento: "12345678",
    telefono: "988888888",
    correo: "maria_rodriguez@gmail.com",
    direccion: "Av. Emancipacion - Dpto 300",
  },
  {
    id: 2,
    apellidos: "Espinoza Chávez",
    nombres: "Juan Carlos",
    tipo_documento: "DNI",
    nro_documento: "12345678",
    telefono: "988888888",
    correo: "juan_espinoza@gmail.com",
    direccion: "Av. Emancipacion - Dpto 300",
  },
  {
    id: 3,
    apellidos: "Vargas Gutiérrez",
    nombres: "César Augusto",
    tipo_documento: "DNI",
    nro_documento: "12345678",
    telefono: "988888888",
    correo: "cesar_vargas@gmail.com",
    direccion: "Av. Emancipacion - Dpto 300",
  },
  {
    id: 4,
    apellidos: "Romero De la Cruz",
    nombres: "Juan Manuel",
    tipo_documento: "DNI",
    nro_documento: "12345678",
    telefono: "988888888",
    correo: "juan_romero@gmail.com",
    direccion: "Av. Emancipacion - Dpto 300",
  },
  {
    id: 5,
    apellidos: "Martínez Reyes",
    nombres: "Pedro Daniel",
    tipo_documento: "DNI",
    nro_documento: "12345678",
    telefono: "988888888",
    correo: "pedro_martinez@gmail.com",
    direccion: "Av. Emancipacion - Dpto 300",
  },
  {
    id: 6,
    apellidos: "Córdova Gómez",
    nombres: "Edwin César",
    tipo_documento: "DNI",
    nro_documento: "12345678",
    telefono: "988888888",
    correo: "edwin_cordova@gmail.com",
    direccion: "Av. Emancipacion - Dpto 300",
  },
  {
    id: 7,
    apellidos: "Ramírez Salazar ",
    nombres: "Walter Fernando",
    tipo_documento: "DNI",
    nro_documento: "12345678",
    telefono: "988888888",
    correo: "walter_ramirez@gmail.com",
    direccion: "Av. Emancipacion - Dpto 300",
  },
  {
    id: 8,
    apellidos: "Rodríguez Mendoza",
    nombres: "María José",
    tipo_documento: "DNI",
    nro_documento: "12345678",
    telefono: "988888888",
    correo: "maria_rodriguez@gmail.com",
    direccion: "Av. Emancipacion - Dpto 300",
  },
  {
    id: 9,
    apellidos: "Espinoza Chávez",
    nombres: "Juan Carlos",
    tipo_documento: "DNI",
    nro_documento: "12345678",
    telefono: "988888888",
    correo: "juan_espinoza@gmail.com",
    direccion: "Av. Emancipacion - Dpto 300",
  },
  {
    id: 10,
    apellidos: "Vargas Gutiérrez",
    nombres: "César Augusto",
    tipo_documento: "DNI",
    nro_documento: "12345678",
    telefono: "988888888",
    correo: "cesar_vargas@gmail.com",
    direccion: "Av. Emancipacion - Dpto 300",
  },
  {
    id: 11,
    apellidos: "Romero De la Cruz",
    nombres: "Juan Manuel",
    tipo_documento: "DNI",
    nro_documento: "12345678",
    telefono: "988888888",
    correo: "juan_romero@gmail.com",
    direccion: "Av. Emancipacion - Dpto 300",
  },
  {
    id: 12,
    apellidos: "Martínez Reyes",
    nombres: "Pedro Daniel",
    tipo_documento: "DNI",
    nro_documento: "12345678",
    telefono: "988888888",
    correo: "pedro_martinez@gmail.com",
    direccion: "Av. Emancipacion - Dpto 300",
  },
  {
    id: 13,
    apellidos: "Córdova Gómez",
    nombres: "Edwin César",
    tipo_documento: "DNI",
    nro_documento: "12345678",
    telefono: "988888888",
    correo: "edwin_cordova@gmail.com",
    direccion: "Av. Emancipacion - Dpto 300",
  },
  {
    id: 14,
    apellidos: "Ramírez Salazar ",
    nombres: "Walter Fernando",
    tipo_documento: "DNI",
    nro_documento: "12345678",
    telefono: "988888888",
    correo: "walter_ramirez@gmail.com",
    direccion: "Av. Emancipacion - Dpto 300",
  },
  {
    id: 15,
    apellidos: "Rodríguez Mendoza",
    nombres: "María José",
    tipo_documento: "DNI",
    nro_documento: "12345678",
    telefono: "988888888",
    correo: "maria_rodriguez@gmail.com",
    direccion: "Av. Emancipacion - Dpto 300",
  },
  {
    id: 15,
    apellidos: "Espinoza Chávez",
    nombres: "Juan Carlos",
    tipo_documento: "DNI",
    nro_documento: "12345678",
    telefono: "988888888",
    correo: "juan_espinoza@gmail.com",
    direccion: "Av. Emancipacion - Dpto 300",
  },
  {
    id: 16,
    apellidos: "Vargas Gutiérrez",
    nombres: "César Augusto",
    tipo_documento: "DNI",
    nro_documento: "12345678",
    telefono: "988888888",
    correo: "cesar_vargas@gmail.com",
    direccion: "Av. Emancipacion - Dpto 300",
  },
  {
    id: 17,
    apellidos: "Romero De la Cruz",
    nombres: "Juan Manuel",
    tipo_documento: "DNI",
    nro_documento: "12345678",
    telefono: "988888888",
    correo: "juan_romero@gmail.com",
    direccion: "Av. Emancipacion - Dpto 300",
  },
  {
    id: 18,
    apellidos: "Martínez Reyes",
    nombres: "Pedro Daniel",
    tipo_documento: "DNI",
    nro_documento: "12345678",
    telefono: "988888888",
    correo: "pedro_martinez@gmail.com",
    direccion: "Av. Emancipacion - Dpto 300",
  },
  {
    id: 19,
    apellidos: "Córdova Gómez",
    nombres: "Edwin César",
    tipo_documento: "DNI",
    nro_documento: "12345678",
    telefono: "988888888",
    correo: "edwin_cordova@gmail.com",
    direccion: "Av. Emancipacion - Dpto 300",
  },
  {
    id: 20,
    apellidos: "Ramírez Salazar ",
    nombres: "Walter Fernando",
    tipo_documento: "DNI",
    nro_documento: "12345678",
    telefono: "988888888",
    correo: "walter_ramirez@gmail.com",
    direccion: "Av. Emancipacion - Dpto 300",
  },
  {
    id: 21,
    apellidos: "Rodríguez Mendoza",
    nombres: "María José",
    tipo_documento: "DNI",
    nro_documento: "12345678",
    telefono: "988888888",
    correo: "maria_rodriguez@gmail.com",
    direccion: "Av. Emancipacion - Dpto 300",
  },
  {
    id: 22,
    apellidos: "Espinoza Chávez",
    nombres: "Juan Carlos",
    tipo_documento: "DNI",
    nro_documento: "12345678",
    telefono: "988888888",
    correo: "juan_espinoza@gmail.com",
    direccion: "Av. Emancipacion - Dpto 300",
  },
  {
    id: 23,
    apellidos: "Vargas Gutiérrez",
    nombres: "César Augusto",
    tipo_documento: "DNI",
    nro_documento: "12345678",
    telefono: "988888888",
    correo: "cesar_vargas@gmail.com",
    direccion: "Av. Emancipacion - Dpto 300",
  },
  {
    id: 24,
    apellidos: "Romero De la Cruz",
    nombres: "Juan Manuel",
    tipo_documento: "DNI",
    nro_documento: "12345678",
    telefono: "988888888",
    correo: "juan_romero@gmail.com",
    direccion: "Av. Emancipacion - Dpto 300",
  },
  {
    id: 25,
    apellidos: "Martínez Reyes",
    nombres: "Pedro Daniel",
    tipo_documento: "DNI",
    nro_documento: "12345678",
    telefono: "988888888",
    correo: "pedro_martinez@gmail.com",
    direccion: "Av. Emancipacion - Dpto 300",
  },
  {
    id: 26,
    apellidos: "Córdova Gómez",
    nombres: "Edwin César",
    tipo_documento: "DNI",
    nro_documento: "12345678",
    telefono: "988888888",
    correo: "edwin_cordova@gmail.com",
    direccion: "Av. Emancipacion - Dpto 300",
  },
  {
    id: 27,
    apellidos: "Ramírez Salazar ",
    nombres: "Walter Fernando",
    tipo_documento: "DNI",
    nro_documento: "12345678",
    telefono: "988888888",
    correo: "walter_ramirez@gmail.com",
    direccion: "Av. Emancipacion - Dpto 300",
  },
]